import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
const font = Open_Sans({ subsets: ["latin"] });
import type { AppProps } from "next/app";
import { ruRU } from "@clerk/localizations";
import { ModalProvider } from "@/components/providers/modal-provider";
import { SocketProvider } from '@/components/providers/socket-provider'
import { QueryProvider } from '@/components/providers/query-provider'
const localization = {
  socialButtonsBlockButton: "Sign In with {{provider|titleize}}",
};

export const metadata: Metadata = {
  title: "Let's Talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ruRU}>
      <html lang="en" suppressHydrationWarning>
      <body className={cn(
          font.className,
          "bg-white dark:bg-[#313338]"
        )}>
            <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false} storageKey="Let's talk theme">
            <SocketProvider>
              <ModalProvider />
              <QueryProvider>
                {children}
              </QueryProvider>
            </SocketProvider>
            </ThemeProvider>
         </body>
      </html>
    </ClerkProvider>
  );
}
